hmpps.sqs:
  provider: localstack
  queues:
    migrationvisits:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationactivities:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationallocations:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationappointments:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationincidents:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationcourtsentencing:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationcoreperson:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationcsra:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationprisonbalance:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationprisonerbalance:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationexternalmovements:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    audit:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventvisits:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventsentencing:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventcoreperson:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventcsra:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventincidents:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      errorVisibilityTimeout: 0
    eventlocations:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventcasenotes:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventfinance:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventalerts:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventcourtsentencing:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventpersonalrelationships:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    domaineventpersonalrelationships:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    domaineventpersoncontacts:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    domaineventprisonerrestrictions:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventorganisations:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventvisitbalance:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventexternalmovements:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    eventofficialvisits:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationofficialvisits:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
    migrationvisitslots:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
